menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView
)


urlpatterns = [
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list')
]

restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView, AllUserRecentItemListView




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^recent/$', AllUserRecentItemListView.as_view(), name='recent'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^muypicky/', include('muyPicky.urls', namespace='muypicky')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

menus/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from muyPicky.models import RestaurantLocation

# Create your models here.
class Item(models.Model):
    # associations
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)
    # real item stuff
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text="separate each item by comma")
    excludes        = models.TextField(blank=True, null=True, help_text="separate each item by comma")
    public          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(',')

    def get_excludes(self):
        return self.contents.split(',')

menus/forms.py
from django import forms

from muyPicky.models import RestaurantLocation
from .models import Item

class ItemForm(forms.ModelForm):

    def __init__(self, user=None, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]

menus/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, View
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Item
from .forms import ItemForm

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            object_list = Item.objects.filter(public=True).order_by('-timestamp')
            return render(request, "home.html", {"object_list": object_list})

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by("-updated")[:5]
        return render(request, "menus/home_feed.html", {'object_list': qs})

class AllUserRecentItemListView(ListView):
    template_name = 'home.html'
    def get_queryset(self):
        return Item.objects.filter(user__is_active=True)

class ItemListView(LoginRequiredMixin, ListView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user) #checks if user is authenticated


class ItemDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)  # checks if user is authenticated


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'menus/form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)  # checks if user is authenticated

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, *kwargs)
        context['title'] = 'Create Item'
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)  # checks if user is authenticated

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, *kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

templates/menus/detail-update.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ form.instance.name }} | Menu Items{% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>{{ form.instance.name }}</h1>
    <p class="lead">{{ form.instance.restaurant.name }}</p>
        {% if form.instance.contents %}
            Contents
            <ul>
                {% for item in form.instance.get_contents %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if form.instance.excludes %}
            Excludes
            <ul>
                {% for item in form.instance.get_excludes %}
                    <li>{{ item }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    <hr />

    <h3>Make Changes</h3>
    {% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}
</body>
</html>

templates/menus/form.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }} | {{ block.super }} {% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>{{ title }}</h1>
{% include 'snippets/form-snippet.html' %}
{% endblock %}
</body>
</html>

templates/menus/home_feed.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% block content %}
    <div class='row'>
        <div class='col-sm-6 text-center offset-sm-3'>
            <h1>Home Feed</h1>
            {% for obj in object_list %}
                <div class='card restaurant'>
                    <h3><a href='{% url "profile:detail" username=obj.user.username %}'>{{ obj.user.username }}</a></h3>
                    <h4>{{ obj.name }}</h4>
                    <p><a href='{% url "profile:detail" username=obj.user.username %}?q={{ obj.restaurant.title }}'>
                        {{ obj.restaurant.title }}</a>|
                        <a href='{% url "profile:detail" username=obj.user.username %}?q={{ obj.restaurant.location }}'>
                            {{ obj.restaurant.location }}</a> |
                        <a href='{% url "profile:detail" username=obj.user.username %}?q={{ obj.restaurant.category }}'>
                            {{ obj.restaurant.category }}</a></p>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}
</body>
</html>

templates/menus/item_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Menu Items{% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="row">
        <div class="col-sm-12 text-left">
            <h1>{{ object.name }}</h1>
            <p class="lead">{{ object.restaurant.name }}</p>
            <ul>
                {% if object.contents %}
                    Contents
                    <ul>
                        {% for item in object.get_contents %}
                            <li>{{ item }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if object.excludes %}
                    Excludes
                    <ul>
                        {% for item in object.get_excludes %}
                            <li>{{ item }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/menus/item_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Menu Items{% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="row">
        <div class="col-sm-12 text-left">
            <h1>Menu Items</h1>
            <p class="lead"><a href="{% url 'menus:create' %}">Add Item</a> </p>
            <ul>
                {% for obj in object_list %}
                    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a></li>
                    {% if obj.contents %}
                        Contents
                        <ul>
                            {% for item in obj.get_contents %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% if obj.excludes %}
                        Excludes
                        <ul>
                            {% for item in obj.get_excludes %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% empty %}
                    <li><a href="{% url 'menus:create' %}">Add Menu Item</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}
</body>
</html>