menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView
)


urlpatterns = [
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list')
]

muyPicky/urls.py
from django.conf.urls import url
from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView,
)


urlpatterns = [
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    #url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    url(r'^$', RestaurantListView.as_view(), name='list')
]

restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView, AllUserRecentItemListView




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^recent/$', AllUserRecentItemListView.as_view(), name='recent'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^muypicky/', include('muyPicky.urls', namespace='muypicky')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

muyPicky/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from .utils import unique_slug_generator
from .validators import validate_category
from django.core.urlresolvers import reverse
from django.db.models import Q

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query): #RestaurantLocation.objects.all().search(query) #RestaurantLocation.objects.filter(something).search()
        if query:
            query = query.strip()
            return self.filter(
                Q(name__icontains=query)|
                Q(location__icontains=query)|
                Q(location__iexact=query)|
                Q(category__icontains=query)|
                Q(category__iexact=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
                ).distinct()
        return self


class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query): #RestaurantLocation.objects.search()
        return self.get_queryset().search(query)

class RestaurantLocation(models.Model):
    owner       = models.ForeignKey(User)
    name        = models.CharField(max_length = 100)
    location    = models.CharField(max_length=100, null=True, blank=True)
    category    = models.CharField(max_length=100, null=True, blank=True, validators=[validate_category])
    description = models.TextField(default="")
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(null=True, blank=True)

    objects = RestaurantLocationManager() #add Mode.objects.all
# shows name of restaurant in admin
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('muypicky:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

muyPicky/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
    name        = forms.CharField()
    location    = forms.CharField(required=False)
    category    = forms.CharField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name == "Hello":
            raise forms.ValidationError('Not a valid name')

class RestaurantLocationCreateForm(forms.ModelForm):
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug'
        ]

muyPicky/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from .forms import RestaurantCreateForm, RestaurantLocationCreateForm
from .models import RestaurantLocation

class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'muyPicky/form.html'
    success_url = '/muypicky/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, *kwargs)
        context['title'] = 'Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'muyPicky/detail-update.html'
    login_url = '/login/'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, *kwargs)
        context['title'] = 'Update Restaurant'
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

templates/muyPicky/detail-update.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ form.instance.title }} | Restaurants | {{ block.super }} {% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="row">
        <div class="col-sm-8 text-center offset-sm-2">
        <h1>{{ form.instance.title }} <p class="lead">{{ form.instance.category }}</p></h1>
        <p>{{ form.instance.location }}</p>
        <p>Description: {{ object.description }}</p>
        <p>{{ form.instance.timestamp }}</p>
        <p>updated: {{ form.instance.updated|timesince }} ago</p>
        </div>
    </div>
        <hr />
    <div class="row">
    <div class="col-sm-8 text-center offset-sm-2">
        <h3>Make Changes</h3>
        {% include 'snippets/form-snippet.html' with form=form %}
    </div>
    </div>
{% endblock %}
</body>
</html>

templates/muyPicky/form.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }} | {{ block.super }} {% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>{{ title }}</h1>
{% include 'snippets/form-snippet.html' %}
{% endblock %}
</body>
</html>

templates/muyPicky/restaurantlocation_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Restaurants | {{ block.super }} {% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>{{ object.name }} <p class="lead">{{ object.category }}</p></h1>
    <p>{{ object.location }}</p>
    <p>Description: {{ object.description }}</p>
    <p>{{ object.timestamp }}</p>
    <p>updated: {{ object.updated|timesince }} ago</p>
{% endblock %}
</body>
</html>

templates/muyPicky/restaurantlocation_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Restaurant List{% endblock %}</title>
</head>
<body>
{% block content %}
<h1>My Restaurants</h1>
    <p class="lead"><a href="{% url 'muypicky:create' %}">Add restaurant</a></p>

    <ul>
    {% for obj in object_list %}
        <li><a href='{{ obj.get_absolute_url }}'>{{ obj }}</a></li>
        <p>{{ obj.location }} {{ obj.category }}</p>
    {% empty %}
        <li><a href="{% url 'muypicky:create' %}">Add Restaurant</a></li>

    {% endfor %}
    </ul>
{% endblock %}
</body>
</html>